spring.application.name=JarvisFs

ollama.url = http://localhost:11434
ollama.model = mistral

spring.main.banner-mode=off
logging.level.org.springframework=OFF
logging.file.name=jarvis.log
logging.level.root=INFO
logging.level.io.github.JarvisFs=DEBUG